<?php

$labels = [];
$labels['plesk'] = 'Control Panel';
$labels['email_forwarding'] = 'Forwarding';
$labels['forwarding_switch'] = 'Switch on mail forwarding';
$labels['email_aliases'] = 'Email Aliases';
$labels['email_autoreply'] = 'Auto Reply';
$labels['autoreply_switch'] = 'Switch on auto reply';
$labels['autoreply_subject'] = 'Auto reply message subject';
$labels['autoreply_content_type'] = 'Message format';
$labels['autoreply_text_plain'] = 'Plain text';
$labels['autoreply_text_html'] = 'HTML';
$labels['autoreply_charset'] = 'Encoding';
$labels['autoreply_charset_utf8'] = 'UTF-8';
$labels['autoreply_message'] = 'Auto reply message text';
$labels['autoreply_forward'] = 'Forward to';
$labels['autoreply_end_date'] = 'Switch off auto reply on';
$labels['autoreply_attachment'] = 'Attach a file';
$labels['email_settings'] = 'Edit';
