<?php

$labels = [];
$labels['plesk_autoreply'] = 'Auto Reply';
$labels['plesk_fowarding'] = 'Fowarding';
$labels['plesk_aliases'] = 'Aliases';
$labels['alias_address'] = 'Email alias';
$labels['add_alias'] = 'Add email alias';
$labels['forwarding_switch'] = 'Enabled';
$labels['fowarding_message'] = 'Forward incoming messages to';
$labels['add_forwarding'] = 'Add email forwarding';
$labels['autoreply_switch'] = 'Enabled';
$labels['autoreply_subject'] = 'Message subject';
$labels['autoreply_content_type'] = 'Email format';
$labels['autoreply_text_plain'] = 'Plain text';
$labels['autoreply_text_html'] = 'HTML';
$labels['autoreply_charset'] = 'Encoding';
$labels['autoreply_charset_utf8'] = 'UTF-8';
$labels['autoreply_message'] = 'Auto reply message';
$labels['autoreply_forward'] = 'Forward to';
$labels['autoreply_end_date'] = 'End auto reply on';
$labels['autoreply_attachment'] = 'Attach a file';
$labels['email_settings'] = 'Edit';
