<?php
$labels = array();
$labels['plesk'] = 'Control Panel';
$labels['email_forwarding'] = 'Forwarding';
$labels['email_forwarding_enabled'] = 'Switch on mail forwarding';
$labels['email_aliases'] = 'Email Aliases';
$labels['email_autoresponder'] = 'Auto Reply';
$labels['email_autoresponder_enabled'] = 'Switch on auto reply';
$labels['email_autoresponder_subject'] = 'Auto reply message subject';
$labels['email_autoresponder_content_type'] = 'Message format';
$labels['email_autoresponder_charset'] = 'Encoding';
$labels['email_autoresponder_message'] = 'Auto reply message text';
$labels['email_autoresponder_forward'] = 'Forward to';
$labels['email_autoresponder_end_date'] = 'Switch off auto reply on';
$labels['email_settings'] = 'Edit Settings';
?>
